language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_script:
  - mvn formatter:validate

after_success:
  - mvn resources:resources jacoco:merge jacoco:report coveralls:report -DrepoToken=OL0MbvrGAzu589jSHioduc5jAOhDxqwGe -Pcoveralls -N -B
